### ISSUE TITLE
로딩바가 실제 로딩 속도와 다르고, 로딩바가 절반부터 시작하는 버그가 있어요

### ISSUE THREAD

**Issue by GGos3** [tempfiles-Team/tempfiles-frontend#43]
ㅈㄱㄴ

**Comment by ananjaemin** [comment]
100% 되도 안되는건 파일이 크거나 네트워크 문제로 백엔드 처리 과정에서 시간이 끌리는것이고
로딩바가 절반부터 시작하는것은 사용자가 인지를 못할정도로 빠르게 올라가서 입니다.
(아마도)

**Comment by ananjaemin** [comment]
개선해보겠습니다.

**Comment by minpeter** [comment]
현제 가능한 조치를 취했으며 10mb 이하의 파일에서는 로딩바의 딜레이가 없는 것을 확인했습니다.
단 파일 용량이 커짐에 따라 백엔드 반응이 느려 실제 로딩과 다르게 보일 수 있는 것을 파악했으며,
- [ ] 로딩 바가 100%가 된 이후 "백엔드 처리 중" 이라는 무한 로딩을 추가할 예정입니다.

**Comment by minpeter** [comment]
다른 문제의 비해 중요도가 낮고 현제 인프라 개선으로 로딩 자체가 줄어들었기 때문에 닫겠습니다.
