### ISSUE TITLE
파일별 다운로드 페이지 라우팅

### ISSUE THREAD

**Issue by minpeter** [tempfiles-Team/tempfiles-frontend#62]
파일 ID를 이용한 페이지 URL 설정

EX) fileID가 Dix7d인 경우,
현제 : https://tempfiles.ml/download
변경후 : https://tempfiles.ml/download?id=Dix7d

**Comment by ananjaemin** [comment]
token있는 파일은 checkpw로 이동되게 해야되나요
@minpeter

**Comment by minpeter** [comment]
아직 모르겠어요... 아마도요..?

**Comment by minpeter** [comment]
file, dl, del에 error, message 말고 redirect_url 필드 추가해드릴까요..?

**Comment by ananjaemin** [comment]
그거는 유연하지않으니 그냥 지금 그대로 하면될듯?

**Comment by minpeter** [comment]
흠... 일단 동작되게 구현하고 개선하든 하죠
우선은 백엔드를 수정해야...
