### ISSUE TITLE
모바일에서 업로드 버튼 누르면..

### ISSUE THREAD

**Issue by GGos3** [tempfiles-Team/tempfiles-frontend#70]
![Screenshot_20221116-011858_Chrome](https://user-images.githubusercontent.com/84070816/201971239-5a3e70bb-23f9-437a-b79f-1af58a1a0270.jpg)

짜잔!
고치세요

**Comment by GGos3** [comment]
업로드만 그런게 아니라 버튼 누르면 다 이러네

**Comment by minpeter** [comment]
Duplicate of #71
