### ISSUE TITLE
파일명이 "　　　　　　　　　　　　　　　" 인 파일 업로드 불가

### ISSUE THREAD

**Issue by GGos3** [tempfiles-team/tempfiles-frontend#78]
https://clipchamp.com/watch/DZYDkee4fpr

**Comment by minpeter** [comment]
업로드 시도하신 파일 kali2005611@gmail.com 으로 보내주세요.
감사합니다

**Comment by GGos3** [comment]
0 byte 파일이라 이메일 안보내지는데 이따 직접 만들어 드릴게요

**Comment by minpeter** [comment]
재현 불가능, close
